spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${ORDER_DB}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

app:
  # Usá env vars si están definidas; si no, defaults razonables
  name: ${APP_NAME:Order Service}
  desc: ${APP_DESC:PizzaExpress - Orders microservice}
  version: ${APP_VERSION:v1}
  url: ${APP_URL:http://localhost:8081}
  dev-name: ${APP_DEV_NAME:PizzaExpress Team}
  dev-email: ${APP_DEV_EMAIL:devs@example.com}
