spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${INVENTORY_DB}
    username: ${INVENTORY_DB_USER}
    password: ${INVENTORY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
